"""add_feed_id_to_item_hash

Revision ID: 1a3aacde9207
Revises: 2cdd130a0aba
Create Date: 2026-01-22 15:20:41.830759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3aacde9207'
down_revision: Union[str, Sequence[str], None] = '2cdd130a0aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_hash', sa.Column('feed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item_hash', 'feed', ['feed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_hash', type_='foreignkey')
    op.drop_column('item_hash', 'feed_id')
    # ### end Alembic commands ###
