"""Update item date to include timezone

Revision ID: 2cdd130a0aba
Revises: 8c2e93e94ed7
Create Date: 2026-01-01 14:25:06.354764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2cdd130a0aba"
down_revision: Union[str, Sequence[str], None] = "8c2e93e94ed7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("itemhash")
    op.alter_column(
        "item",
        "date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "item",
        "date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.create_table(
        "itemhash",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("hash", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("itemhash_pkey")),
    )
    # ### end Alembic commands ###
