name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.11
  #     - name: Install dependencies
  #       run: |
  #         pip install -r requirements-dev.txt
  #     - name: Run tests
  #       run: pytest
  deploy:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Deploy with SSH
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd github/gkfeed/parser
            pipenv run gitup
            pipenv run drestart
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
